[package]
name = "wasi-io"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-io-async = { workspace = true, features = ["std"] }
wasi = { workspace = true }
wasi-executor = { path = "../wasi-executor" }
