[package]
name = "wasync"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { workspace = true }
wasi = { workspace = true }
log = { workspace = true }

embedded-io-async = { workspace = true, features = ["std"], optional = true }
edge-nal = { workspace = true, optional = true }

[features]
io = ["dep:embedded-io-async"]
net = ["io", "dep:edge-nal"]
fs = ["io"]
